[package]
name = "hinjaku"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hinjaku"
path = "src/main.rs"

[dependencies]
eframe = "0.27"
egui = "0.27"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "gif", "bmp", "webp", "tiff"] }
zip = "2.1"
sevenz-rust = "0.6"
rfd = "0.14"
anyhow = "1"
thiserror = "1.0"
log = "0.4"
rust-ini = "0.21"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_DataExchange",
    "Win32_System_IO",
    "Win32_Security",
    "Win32_System_SystemServices",
    "Win32_System_WindowsProgramming",
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging_DesktopWindow", # GetActiveWindow のために追加
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_ProcessStatus",
] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
