[package]
name = "hinjaku"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hinjaku"
path = "src/main.rs"

[dependencies]
eframe = "0.27"
egui = "0.27"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "gif", "bmp", "webp", "tiff"] }
zip = "2.1"
sevenz-rust = "0.6"
rfd = "0.14"
anyhow = "1"
rust-ini = "0.21"

#[target.'cfg(windows)'.dependencies] は Windows 環境でのみこのライブラリを読み込む指定です
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
