use eframe::egui;

pub struct KeyboardState {
    pub left: bool,
    pub right: bool,
    pub up: bool,
    pub dn: bool,
    pub enter: bool,
    pub esc: bool,
    pub t: bool,
    pub fit_t: bool,
    pub zin: bool,
    pub zout: bool,
    pub manga_t: bool,
    pub rcw: bool,
    pub rccw: bool,
    pub pgup: bool,
    pub pgdn: bool,
    pub p: bool,
    pub n: bool,
    pub s: bool,
    pub home: bool,
    pub end: bool,
    pub bs: bool,
    pub e: bool,
    pub i: bool,
    pub alt: bool,
    pub y: bool,
    pub q_key: bool,
    pub ctrl_w: bool,
    pub b: bool,
}

pub fn gather_input(ctx: &egui::Context) -> KeyboardState {
    ctx.input(|i| KeyboardState {
        left: i.key_pressed(egui::Key::ArrowLeft),
        right: i.key_pressed(egui::Key::ArrowRight),
        up: i.key_pressed(egui::Key::ArrowUp),
        dn: i.key_pressed(egui::Key::ArrowDown),
        enter: i.key_pressed(egui::Key::Enter),
        esc: i.key_pressed(egui::Key::Escape),
        t: i.key_pressed(egui::Key::T),
        fit_t: i.key_pressed(egui::Key::F),
        zin: i.key_pressed(egui::Key::Plus) || i.key_pressed(egui::Key::Equals),
        zout: i.key_pressed(egui::Key::Minus),
        manga_t: i.key_pressed(egui::Key::M) || i.key_pressed(egui::Key::Space),
        rcw: i.key_pressed(egui::Key::R) && !i.modifiers.ctrl,
        rccw: i.key_pressed(egui::Key::R) && i.modifiers.ctrl,
        pgup: i.key_pressed(egui::Key::PageUp),
        pgdn: i.key_pressed(egui::Key::PageDown),
        p: i.key_pressed(egui::Key::P),
        n: i.key_pressed(egui::Key::N),
        s: i.key_pressed(egui::Key::S),
        home: i.key_pressed(egui::Key::Home),
        end: i.key_pressed(egui::Key::End),
        bs: i.key_pressed(egui::Key::Backspace),
        e: i.key_pressed(egui::Key::E),
        i: i.key_pressed(egui::Key::I),
        alt: i.modifiers.alt,
        y: i.key_pressed(egui::Key::Y),
        q_key: i.key_pressed(egui::Key::Q),
        ctrl_w: i.modifiers.ctrl && i.key_pressed(egui::Key::W),
        b: i.key_pressed(egui::Key::B),
    })
}